### ISSUE TITLE
안녕하세요. 해당 모델을 사용하려는 학생입니다.

### ISSUE THREAD

**Issue by Youngseo-Jeon0313** [eunsour/engtokor-transliterator#1]
해당 레포 덕분에 한영 발음 변환기에 많은 인사이트를 얻었습니다! 매우 감사드립니다. 

다름이 아니라 모델을 돌리면 아래와 같은 오류가 뜨는데, 아무래도 HuggingFace 내에 해당 데이터들이 없는 것으로 추측됩니다. 해결방법이 있을까요??

OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./outputs/best_model.

**Comment by eunsour** [comment]
https://github.com/eunsour/engtokor-transliterator/blob/1fd5bcfe05e5348457ceccd0217ab559c7bfcf0b/transliteration.py#L29

이 부분에서 에러가 나시는 것 같은데 훈련 없이 모델을 사용하시려면 https://huggingface.co/eunsour/en-ko-transliterator 여기서 모델을 다운받으셔서 변수 선언 하시면 될 것 같습니다.

**Comment by Youngseo-Jeon0313** [comment]
헉 감사드립니다! 해당 부분을
pretrained_model_path = "eunsour/en-ko-transliterator"
로 바꾸니 해결되었어요!

2주동안 이 부분 보면서 오류 트래킹 하고 있었는데 🥲 진작 여쭤볼 걸 그랬네요 ㅠㅠ
